### ISSUE TITLE
default NAND environment bug

### ISSUE THREAD

**Issue by QB4-dev** [SoMLabs/somlabs-uboot-imx#3]
There is a bug in environment default settings NAND version
```
U-Boot 2018.09+fslc+g2b9de64 (Apr 30 2019 - 11:41:23 +0000)

CPU:   Freescale i.MX6ULL rev1.0 792 MHz (running at 396 MHz)
CPU:   Industrial temperature grade (-40C to 105C) at 46C
Reset cause: POR
Model: SomLabs i.MX6 ULL Visionsom
Board: SomLabs visionsom 6ull
DRAM:  512 MiB
NAND:  512 MiB
Loading Environment from NAND... *** Warning - bad CRC, using default environment

In:    serial
Out:   serial
Err:   serial
Net:   FEC0 [PRIME]
Error: FEC0 address not set.

Somlabs iMX6ULL # printenv
baudrate=115200
board_name=VISIONSOM
board_rev=6ULL
boot_fdt=try
bootargs=console=ttymxc0,115200 ubi.mtd=ubi root=ubi0:rootfs rootfstype=ubifs rootwait=1 rw bootcmd=mtdparts default; ubi part ubi; ubifsmount ubi0:rootfs;ubifsload ${loadaddr} /boot/zImage;ubifsload ${fdt_addr} /boot/${fdt_file};bootz ${loadaddr} - ${fdt_addr}
bootcmd_mfg=run mfgtool_args;bootz ${loadaddr} ${initrd_addr} ${fdt_addr};
bootdelay=5
console=ttymxc0
ethact=FEC0
ethprime=FEC0
fdt_addr=0x83000000
fdt_file=somlabs-visionsom-6ull-nand.dtb
fdt_high=0xffffffff
fdtcontroladdr=9ef36f20
initrd_addr=0x83800000
initrd_high=0xffffffff
ip_dyn=yes
loadaddr=0x82000000
mfgtool_args=setenv bootargs console=${console},${baudrate} rdinit=/linuxrc g_mass_storage.stall=0 g_mass_storage.removable=1 g_mass_storage.file=/fat g_mass_storage.ro=1 g_mass_storage.idVendor=0x066F g_mass_storage.idProduct=0x37FF g_mass_storage.iSerialNumber="" mtdparts=gpmi-nand:4m(boot),-(ubi)
ver=U-Boot 2018.09+fslc+g2b9de64 (Apr 30 2019 - 11:41:23 +0000)
videomode=video=ctfb:x:800,y:480,depth:24,pclk:30000,le:40,ri:40,up:29,lo:13,hs:48,vs:3,sync:s,vmode:0

Environment size: 1106/131068 bytes
```

In this line __bootargs__ and __bootcmd__ are mixed up
```
bootargs=console=ttymxc0,115200 ubi.mtd=ubi root=ubi0:rootfs rootfstype=ubifs rootwait=1 rw bootcmd=mtdparts default; ubi part ubi; ubifsmount ubi0:rootfs;ubifsload ${loadaddr} /boot/zImage;ubifsload ${fdt_addr} /boot/${fdt_file};bootz ${loadaddr} - ${fdt_addr}
```
Also if  __bootargs__ look like this:
```
bootargs=console=ttymxc0,115200 ubi.mtd=ubi root=ubi0:rootfs rootfstype=ubifs rootwait=1 rw
```
Linux doesn't know NAND partition scheme. I am not sure if something like `mtdparts=gpmi-nand:4m(boot),-(ubi)` is missing for cmdline arguments

**Comment by myfreescalewebpage** [comment]
Hello @QB4-dev 
I'm working with yocto (see https://github.com/SoMLabs/meta-somlabs/issues/2) and just seen your issue. I have the same problem. Have you got found a solution since you opened this issue ?
Regards,
Joel

**Comment by voloviq** [comment]
Please try to use 'warrior' distro, I created two new configurations with NAND 256MB and 512MB. Let me know.
Regards

**Comment by QB4-dev** [comment]
@myfreescalewebpage
Hi Joel
Unfortunately I didn't managed to write u-boot correctly to NAND version of visionsom6ull. 
All i did was to generate ubi system image from Yocto, and burn it from tftp-hpa server using methods from this tutorial: http://www.emsyslabs.com/somlabs-nand-programming/

Image was written to memory correctly, Linux started, but after reset I needed to write bootloader to RAM using uuu again. 
I've contacted with engineer from SOMLabs and he advised me to use linux-imx kernel which exports nand memory properties to debugfs(from nand-gpmi driver), and from there tool named imx-kobs used to write bootloader will 
know proper NAND memory geometry. I haven't enough time to change to older kernel in my project and switched to EMMC version for now. I'll probably will try to write images to NAND modules in future for cutting costs.

By the way. To resolve problem from this issue caused by typo in default uboot enviroment settings you need to set u-boot environment correctly:
`setenv bootargs "console=ttymxc0,115200 ubi.mtd=ubi root=ubi0:rootfs rootfstype=ubifs rootwait=1 rw"`

`setenv bootcmd "mtdparts default; ubi part ubi; ubifsmount ubi0:rootfs;ubifsload ${loadaddr} /boot/zImage;ubifsload ${fdt_addr} /boot/${fdt_file};bootz ${loadaddr} - ${fdt_addr}"`

also if you didin't set NAND partition scheme in device-tree and Linux kernel complains that cannot find nand partitions add  this at the end of __bootargs__ value
`mtdparts=gpmi-nand:4m(boot),-(ubi)`

And one more thing: 
Recently SOMLabs created a tool to write images on NAND boards, but I didnn't tested it yet:
https://wiki.somlabs.com/index.php/How_to_write_image_to_VisionSOM-6ULL_NAND_memory_using_UUU_tool_on_Linux

**Comment by myfreescalewebpage** [comment]
Hi @QB4-dev 
Thanks for your message, as discussed here https://github.com/SoMLabs/meta-somlabs/issues/2 I have succeeded throw USB with the tool proposed by SOMLABS recently.
I will be in vacation for two weeks but then I will finish this job.
Regards,
Joel
