### ISSUE TITLE
VisionSOM-8Mmini: Booting Android from USDHC1

### ISSUE THREAD

**Issue by rhardik** [SoMLabs/somlabs-uboot-imx#6]
Hi,

I'm having  VisionSOM-8Mmini module and wants to boot the Android.
But emmc size is 8 GB and recommended is 16 GB so i guess that's why flashing code to emmc is getting failed.

So I prepared a bootable SD card using below command 
`sudo ./device/fsl/common/tools/fsl-sdcard-partition.sh -D out/target/product/visionsom_8mm/ -f imx8mm /dev/sdX`

But USDHC1 seems not added as a boot device in uboot.

Could you please point me to the code where I can add USDHC1 as boot device?

Thanks,
Hardik

**Comment by kchojnowski** [comment]
Hi,

the mmc boot device is programmed in OTP fuse bits, so you are not able to change it. However you should be able to modify u-boot to load the system from another mmc interface. The system interface configuration is defined in the following files:
board/somlabs/visionsom-8mm/visionsom-8mm.c
include/configs/visionsom_8mm.h

You will also need to make changes in the u-boot and kernel device trees to configure all needed interfaces. In such configuration your u-boot needs to be programmed in eMMC, and the full system image should be loaded from the external SD-card.

Regards,
Krzysztof
